baseurl = "https://liangliu.me/"
languageCode = "en-us"
title = "Liang Liu's blog"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-166874069-1"
disqusShortname = "liul85"
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/liul85"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/liul85"

[params]
    mainSections = ["post"]

    description = ""

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

